version: "3.8"
services:
  user-control:
    build: ./

    ports:
      - "8080:8080"
    volumes:
      - ./:/app
      - /node_modules
    container_name: user-control
    stdin_open: true
    tty: true